import Logo from "@/components/ui/Logo";
import Head from "next/head";

Logo;

const Home = () => {
  return (
    <div>
      <Head>
        <title>ThirdSpace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
      </Head>

      <Logo />

      {/* <h1 className="text-center mt-10 text-3xl">ThirdSpace</h1> */}
    </div>
  );
};

export default Home;
