import { arrowUp, signIn, signUp } from "@/assets";
import Logo from "@/components/ui/Logo";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
signIn;

type Props = {};

const HomePage = (props: Props) => {
  return (
    <>
      <Head>
        <title>ThirdSpace </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
      </Head>

      <Logo />

      <h1 className="text-center text-white font-medium text-8xl  mt-20 font-roboto">
        Earn Rewards for <br /> Your Skills
      </h1>

      <p className="text-center text-white font-normal  mt-6 font-inter  text-sm   ">
        Connect your GitHub account, join bounties, and earn rewards for your
        coding skills. Our smart <br /> contracts ensure fair payouts and easy
        payment processing
      </p>

      <div className="flex flex-col md:flex-row text-white gap-10 justify-center mt-10">
        <Link href="/">
          <button className="">
            <Image src={signIn} alt="signUp" width={150} />
          </button>
        </Link>
        <Link href="/">
          <button className="">
            <Image src={signUp} alt="signUp" width={150} />
          </button>
        </Link>
      </div>
    </>
  );
};

export default HomePage;
