import { arrowUp } from "@/assets";
import Logo from "@/components/Ui/Logo";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

type Props = {};

const HomePage = (props: Props) => {
  return (
    <>
      <Head>
        <title>Home </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
      </Head>

      <Logo />

      <h1 className="text-center text-white text-8xl  mt-20">
        Earn Rewards for <br /> Your Skills
      </h1>

      <p className="text-center text-white text-md mt-4 ">
        Connect your GitHub account, join bounties, and earn rewards for your
        coding skills. Our smart <br /> contracts ensure fair payouts and easy
        payment processing
      </p>

      <div className="flex flex-col md:flex-row text-white gap-10 justify-center mt-10">
        <Link href="/">
          <button className="py-2 px-6 rounded-full border border-white">
            <div className="flex flew-row">
              <h2> Sign In</h2>
            </div>
          </button>
        </Link>
        <Link href="/">
          <button className="py-2 px-6 rounded-full border border-white">
            Sign Up
          </button>
        </Link>
      </div>
    </>
  );
};

export default HomePage;
